definitions:
  dto.AddTagInPut:
    properties:
      createdBy:
        type: string
      modified_by:
        type: string
      name:
        type: string
      state:
        type: integer
    type: object
  dto.DeleteTagInPut:
    properties:
      id:
        type: integer
    type: object
  dto.EditTagInPut:
    properties:
      id:
        type: integer
      modified_by:
        type: string
      name:
        type: string
      state:
        type: integer
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
info:
  contact: {}
  description: An example of gin
  license:
    name: MIT
    url: https://github.com/EDDYCJY/go-gin-example/blob/master/LICENSE
  termsOfService: https://github.com/EDDYCJY/go-gin-example
  title: Golang Gin API
  version: "1.0"
paths:
  /api/v1/add_tag:
    post:
      parameters:
      - description: AddTagInPut
        in: body
        name: tag
        required: true
        schema:
          $ref: '#/definitions/dto.AddTagInPut'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Add article tag
  /api/v1/delete_tag:
    post:
      parameters:
      - description: ID
        in: body
        name: id
        required: true
        schema:
          $ref: '#/definitions/dto.DeleteTagInPut'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Delete article tag
  /api/v1/edit_tag:
    post:
      parameters:
      - description: EditTagInPut
        in: body
        name: tag
        required: true
        schema:
          $ref: '#/definitions/dto.EditTagInPut'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Edit tag
  /api/v1/get_tags:
    get:
      parameters:
      - in: query
        name: name
        type: string
      - in: query
        name: pageNum
        type: integer
      - in: query
        name: pageSize
        type: integer
      - in: query
        name: state
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get multiple article tags
swagger: "2.0"
